### ISSUE TITLE
Would you take samples of "your dataset format" for training customer's dataset?

### ISSUE THREAD

**Issue by BenoitKAO** [jingtianyilong/YOLOv4-pytorch#5]
Thank you for your marvelous work.

Would you take samples of "your dataset format" for training customer's dataset?

images/00001.png x1,y1,x2,y2,class_id

A.
x1==>centroid of the region, "ratio" of the whole image,
y1==>centroid of the region, "ratio" of the whole image,
x2==>centroid of the region, "ratio" of the whole image,
y2==>centroid of the region, "ratio" of the whole image,

B.
x1==>centroid of the region, "pixel position" of the whole image,
y1==>centroid of the region, "pixel position" of the whole image,
x2==>centroid of the region, "pixel position" of the whole image,
y2==>centroid of the region, "pixel position" of the whole image,

Which is for the customer's dataset format?

Thank you again.

Any help is appreciated.

**Comment by jingtianyilong** [comment]
You made a good point. I should declare more detailed information.
x1, y1 refer to the coordinates of top left corner.
x2, y2 refer to the coordinates of bottom right corner.
All the coordinates are pixel wise location on the original image.

And I would strongly suggest that you also name the image with number. Or else you should rewrite this to make coco eval tool work properly.
https://github.com/jingtianyilong/YOLOv4-pytorch/blob/34aebf6193c309dacff00b5152291ffc1e7d4984/utils/datasets.py#L201-L202
I would update the README.md respectively

**Comment by BenoitKAO** [comment]
Thank you very much for your reply and your instructions.
